#!/bin/bash

CODE=$(whiptail --title "Two Factor Authentication" \
     --passwordbox "Enter code:" 8 32 \
     3>&1 1>&2 2>&3 3>&-); clear
USEC=$(sed -n 1p $HOME/.google_authenticator)
TOTP=$(oathtool --totp -b $USEC)

if [[ $CODE -ne $TOTP ]]; then whiptail --title "Error Detected" --msgbox "Wrong Code!" --ok-button "exit" 5 24; clear; exit 1

  else

    OPT=$(Whiptail --menu "Select Target:" 16 24 8 \
        1 "Docker 1" \
        2 "Docker 7" \
        3 "DNS main" \
        4 "K8s master" \
        5 "NAS" \
        6 "Exit" \
        3>&1 1>&2 2>&3 3>&-); clear
    case $OPT in
         1) ssh root@10.10.100.2 ; exit ;;
         2) ssh root@10.10.100.3 ; exit ;;
         3) ssh root@10.10.100.4 ; exit ;;
         4) ssh root@10.10.100.5 ; exit ;;
         5) ssh root@10.10.100.6 ; exit ;;
         *) exit ;;
    esac
fi
