#!/bin/bash
#
echo " Adding aliases to your bash and a new prompt"
# Add to or change the bash commands:
wget https://raw.githubusercontent.com/nallej/MyJourney/main/.bash_aliases
# And also the personal bash prompt:
wget https://raw.githubusercontent.com/nallej/MyJourney/main/.bash_prompt
# Activate the changes
. ~/.bash_aliases
