#!/usr/bin/env bash
#
# Author: Nalle (CasaUrsus)
# Date: August 2, 2024
# License: MIT

# Function setting the log files
setLOG(){
    if [ -f "$logFILE" ]; then
       if (whiptail --backtitle "$backTEXT" --title "Log File Dialog" --defaultno --yesno \
            "\n⚠️   You have a log file: $logFILE \
            \n- Do you like to proceed by Overwriting it or Appending to it" \
            8 78 --no-button "Append" --yes-button "Overwrite"); then
            echo "${blub}>>>> Started the Install  $(date +"%F %T") ${end}" > $logFILE
        else
            echo "${blub}>>>> Started the Install  $(date +"%F %T") ${end}" >> $logFILE
        fi
    else
        echo "${blub}>>>> Started the Install  $(date +"%F %T") ${end}" > $logFILE
    fi
}

export -f setLOG
