---
version: '3'
# Log reader, deploy from Portainer or by hand
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    restart: unless-stopped
    networks:
      - pihalla
# networks to be used by service
networks:
  pihalla:
    external: true
...
